from typing import Dict, List

# Mock Database of Activities
ACTIVITIES_DB: Dict[str, List[dict]] = {
    "comida": [
        {"title": "Tour de comida callejera", "icon": "fa-utensils", "image": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80"},
        {"title": "Cena en restaurante local", "icon": "fa-utensils", "image": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80"},
        {"title": "Clase de cocina tradicional", "icon": "fa-utensils", "image": "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=1200&q=80"},
        {"title": "Mercado gastronómico", "icon": "fa-utensils", "image": "https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?auto=format&fit=crop&w=800&q=80"}
    ],
    "arte": [
        {"title": "Museo de Arte Moderno", "icon": "fa-palette", "image": "https://www.moma.org/assets/visit/entrance-image--museum-crop-7516b01003659172f2d9dbc7a6c2e9d9.jpg"},
        {"title": "Galería de arte contemporáneo", "icon": "fa-palette", "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Alte_Nationalgalerie_abends_%28Zuschnitt%29.jpg/1200px-Alte_Nationalgalerie_abends_%28Zuschnitt%29.jpg"},
        {"title": "Tour de Street Art", "icon": "fa-spray-can", "image": "https://bogota.gov.co/sites/default/files/styles/1050px/public/eventos/2024-06/distrito-grafiti-bienvenidos.png"},
        {"title": "Teatro Histórico", "icon": "fa-masks-theater", "image": "https://images.adsttc.com/media/images/5899/d0b6/e58e/cead/d600/0167/newsletter/CC0_Public_Domain_opera-594592.jpg?1486475429"}
    ],
    "paseo": [
        {"title": "Caminata por el centro histórico", "icon": "fa-person-walking", "image": "https://images.unsplash.com/photo-1505761671935-60b3a7427bad?auto=format&fit=crop&w=800&q=80"},
        {"title": "Paseo en bicicleta", "icon": "fa-bicycle", "image": "https://images.prismic.io/peopleforbikes/aa9565ca-37cf-4116-98d8-9cfef0d78744_bigger-street-1024x768.jpg?auto=compress,format"},
        {"title": "Jardín Botánico", "icon": "fa-leaf", "image": "https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?auto=format&fit=crop&w=800&q=80"},
        {"title": "Parque Central", "icon": "fa-tree", "image": "https://images.unsplash.com/photo-1496347646636-ea47f7d6b37b?auto=format&fit=crop&w=800&q=80"}
    ],
    "vistas": [
        {"title": "Mirador Panorámico", "icon": "fa-binoculars", "image": "https://images.unsplash.com/photo-1506953823976-52e1fdc0149a?auto=format&fit=crop&w=800&q=80"},
        {"title": "Atardecer en la playa/río", "icon": "fa-sun", "image": "https://images.unsplash.com/photo-1472120435266-53107fd0c44a?auto=format&fit=crop&w=800&q=80"},
        {"title": "Torre de observación", "icon": "fa-tower-observation", "image": "https://images.unsplash.com/photo-1486325212027-8081e485255e?auto=format&fit=crop&w=800&q=80"}
    ],
    "cafes": [
        {"title": "Cafetería Histórica", "icon": "fa-mug-hot", "image": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80"},
        {"title": "Cata de café", "icon": "fa-mug-saucer", "image": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80"},
        {"title": "Brunch con vista", "icon": "fa-utensils", "image": "https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?auto=format&fit=crop&w=1200&q=80"}
    ],
    "museos": [
        {"title": "Museo de Historia", "icon": "fa-landmark", "image": "https://images.unsplash.com/photo-1566127444979-b3d2b654e3d7?auto=format&fit=crop&w=800&q=80"},
        {"title": "Museo de Ciencias", "icon": "fa-flask", "image": "https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=800&q=80"},
        {"title": "Planetario", "icon": "fa-star", "image": "https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3?auto=format&fit=crop&w=800&q=80"}
    ],
    "aventura": [
        {"title": "Trekking a mirador", "icon": "fa-mountain", "image": "https://bogota.gov.co/sites/default/files/2022-08/la-aguadora.jpg"},
        {"title": "Tour en kayak", "icon": "fa-water", "image": "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/0b/25/fe/ab.jpg"},
        {"title": "Ruta en globo aerostático", "icon": "fa-location-arrow", "image": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80"}
    ],
    "nocturna": [
        {"title": "Bar de cocteles de autor", "icon": "fa-champagne-glasses", "image": "https://media.ooka.com/media/magefan_blog/dubaiatnight.jpg"},
        {"title": "Club de jazz íntimo", "icon": "fa-music", "image": "https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=800&q=80"},
        {"title": "Noche de rooftop con vista", "icon": "fa-moon", "image": "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=800&q=80"}
    ],
    "compras": [
        {"title": "Mercado de diseño local", "icon": "fa-shopping-bag", "image": "https://byfood.b-cdn.net/api/public/assets/9299/content"},
        {"title": "Barrio de boutiques", "icon": "fa-tag", "image": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80"},
        {"title": "Outlet de marcas", "icon": "fa-store", "image": "https://images.unsplash.com/photo-1523475472560-d2df97ec485c?auto=format&fit=crop&w=800&q=80"}
    ],
    "playa": [
        {"title": "Día de playa y snorkel", "icon": "fa-umbrella-beach", "image": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80"},
        {"title": "Paseo en velero al atardecer", "icon": "fa-ship", "image": "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=800&q=80"},
        {"title": "Clase de surf para principiantes", "icon": "fa-person-swimming", "image": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80"}
    ],
    "bienestar": [
        {"title": "Sesión de spa y sauna", "icon": "fa-leaf", "image": "https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=800&q=80"},
        {"title": "Clase de yoga al amanecer", "icon": "fa-heart", "image": "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=80"},
        {"title": "Baños termales naturales", "icon": "fa-water", "image": "https://images.unsplash.com/photo-1468413253725-0d5181091126?auto=format&fit=crop&w=800&q=80"}
    ]
}

# Pequeña base de datos local de ciudades para autocompletar y fallback
LOCAL_CITY_FALLBACKS: List[str] = [
    "Nueva York, Estados Unidos",
    "Los Ángeles, Estados Unidos",
    "San Francisco, Estados Unidos",
    "Chicago, Estados Unidos",
    "Miami, Estados Unidos",
    "Nueva Orleans, Estados Unidos",
    "Toronto, Canadá",
    "Vancouver, Canadá",
    "Montreal, Canadá",
    "Ciudad de México, México",
    "Guadalajara, México",
    "Monterrey, México",
    "Buenos Aires, Argentina",
    "Córdoba, Argentina",
    "Rosario, Argentina",
    "Santiago, Chile",
    "Valparaíso, Chile",
    "Lima, Perú",
    "Cusco, Perú",
    "La Paz, Bolivia",
    "São Paulo, Brasil",
    "Río de Janeiro, Brasil",
    "Brasilia, Brasil",
    "Bogotá, Colombia",
    "Medellín, Colombia",
    "Quito, Ecuador",
    "Londres, Reino Unido",
    "Manchester, Reino Unido",
    "Edimburgo, Reino Unido",
    "Dublín, Irlanda",
    "París, Francia",
    "Lyon, Francia",
    "Marsella, Francia",
    "Madrid, España",
    "Barcelona, España",
    "Valencia, España",
    "Sevilla, España",
    "Lisboa, Portugal",
    "Oporto, Portugal",
    "Ámsterdam, Países Bajos",
    "Bruselas, Bélgica",
    "Ginebra, Suiza",
    "Zúrich, Suiza",
    "Berlín, Alemania",
    "Múnich, Alemania",
    "Hamburgo, Alemania",
    "Viena, Austria",
    "Praga, República Checa",
    "Budapest, Hungría",
    "Varsovia, Polonia",
    "Cracovia, Polonia",
    "Atenas, Grecia",
    "Santorini, Grecia",
    "Dubrovnik, Croacia",
    "Tokio, Japón",
    "Kioto, Japón",
    "Osaka, Japón",
    "Seúl, Corea del Sur",
    "Busan, Corea del Sur",
    "Pekín, China",
    "Shanghái, China",
    "Hong Kong, China",
    "Singapur, Singapur",
    "Bangkok, Tailandia",
    "Chiang Mai, Tailandia",
    "Hanoi, Vietnam",
    "Ciudad Ho Chi Minh, Vietnam",
    "Nueva Delhi, India",
    "Mumbai, India",
    "Jaipur, India",
    "Bali, Indonesia",
    "Dubái, Emiratos Árabes Unidos",
    "Sídney, Australia",
    "Melbourne, Australia",
    "Brisbane, Australia",
    "Auckland, Nueva Zelanda",
    "Queenstown, Nueva Zelanda",
    "Boston, Estados Unidos",
    "Filadelfia, Estados Unidos",
    "Washington D. C., Estados Unidos",
    "Atlanta, Estados Unidos",
    "Dallas, Estados Unidos",
    "Houston, Estados Unidos",
    "Austin, Estados Unidos",
    "Denver, Estados Unidos",
    "Seattle, Estados Unidos",
    "Portland, Estados Unidos",
    "Phoenix, Estados Unidos",
    "San Diego, Estados Unidos",
    "Las Vegas, Estados Unidos",
    "Orlando, Estados Unidos",
    "Tampa, Estados Unidos",
    "Salt Lake City, Estados Unidos",
    "San Antonio, Estados Unidos",
    "Baltimore, Estados Unidos",
    "Detroit, Estados Unidos",
    "Cleveland, Estados Unidos",
    "Pittsburgh, Estados Unidos",
    "Charlotte, Estados Unidos",
    "Nashville, Estados Unidos",
    "Memphis, Estados Unidos",
    "Minneapolis, Estados Unidos",
    "Kansas City, Estados Unidos",
    "Saint Louis, Estados Unidos",
    "Albuquerque, Estados Unidos",
    "Santa Fe, Estados Unidos",
    "Boise, Estados Unidos",
    "Anchorage, Estados Unidos",
    "Honolulu, Estados Unidos",
    "Kahului, Estados Unidos",
    "Lihue, Estados Unidos",
    "Quebec, Canadá",
    "Ottawa, Canadá",
    "Calgary, Canadá",
    "Edmonton, Canadá",
    "Winnipeg, Canadá",
    "Halifax, Canadá",
    "Cancún, México",
    "Tijuana, México",
    "Puebla, México",
    "Mérida, México",
    "Oaxaca, México",
    "San Luis Potosí, México",
    "Toluca, México",
    "San José, Costa Rica",
    "Panamá, Panamá",
    "Santo Domingo, República Dominicana",
    "San Juan, Puerto Rico",
    "La Habana, Cuba",
    "Kingston, Jamaica",
    "Nassau, Bahamas",
    "Montevideo, Uruguay",
    "Punta del Este, Uruguay",
    "Asunción, Paraguay",
    "Cartagena, Colombia",
    "Barranquilla, Colombia",
    "Cali, Colombia",
    "Guayaquil, Ecuador",
    "Cuenca, Ecuador",
    "Arequipa, Perú",
    "Iquitos, Perú",
    "Manaos, Brasil",
    "Salvador, Brasil",
    "Fortaleza, Brasil",
    "Recife, Brasil",
    "Belo Horizonte, Brasil",
    "Curitiba, Brasil",
    "Porto Alegre, Brasil",
    "Florianópolis, Brasil",
    "Florencia, Italia",
    "Nápoles, Italia",
    "Milán, Italia",
    "Turín, Italia",
    "Bolonia, Italia",
    "Pisa, Italia",
    "Venecia, Italia",
    "Verona, Italia",
    "Niza, Francia",
    "Cannes, Francia",
    "Burdeos, Francia",
    "Toulouse, Francia",
    "Lille, Francia",
    "Estrasburgo, Francia",
    "Frankfurt, Alemania",
    "Colonia, Alemania",
    "Düsseldorf, Alemania",
    "Stuttgart, Alemania",
    "Núremberg, Alemania",
    "Dresde, Alemania",
    "Leipzig, Alemania",
    "Copenhague, Dinamarca",
    "Oslo, Noruega",
    "Bergen, Noruega",
    "Estocolmo, Suecia",
    "Gotemburgo, Suecia",
    "Helsinki, Finlandia",
    "Tallin, Estonia",
    "Riga, Letonia",
    "Vilna, Lituania",
    "Bucarest, Rumanía",
    "Sofía, Bulgaria",
    "Belgrado, Serbia",
    "Sarajevo, Bosnia y Herzegovina",
    "Skopje, Macedonia del Norte",
    "Liubliana, Eslovenia",
    "Zagreb, Croacia",
    "Zadar, Croacia",
    "Split, Croacia",
    "Estambul, Turquía",
    "Ankara, Turquía",
    "Antalya, Turquía",
    "Esmirna, Turquía",
    "Göreme, Turquía",
    "Tiflis, Georgia",
    "Ereván, Armenia",
    "Bakú, Azerbaiyán",
    "Tel Aviv, Israel",
    "Jerusalén, Israel",
    "Amán, Jordania",
    "Doha, Catar",
    "Kuwait, Kuwait",
    "Mascate, Omán",
    "Marrakech, Marruecos",
    "Casablanca, Marruecos",
    "El Cairo, Egipto",
    "Luxor, Egipto",
    "Nairobi, Kenia",
    "Kampala, Uganda",
    "Addis Abeba, Etiopía",
    "Dar es Salaam, Tanzania",
    "Ciudad del Cabo, Sudáfrica",
    "Johannesburgo, Sudáfrica",
    "Dakar, Senegal",
    "Accra, Ghana",
    "Taipéi, Taiwán",
    "Kaohsiung, Taiwán",
    "Taichung, Taiwán",
    "Manila, Filipinas",
    "Cebú, Filipinas",
    "Kuala Lumpur, Malasia",
    "Penang, Malasia",
    "Malaca, Malasia",
    "Phnom Penh, Camboya",
    "Siem Riep, Camboya",
    "Vientián, Laos",
    "Luang Prabang, Laos",
    "Yangón, Birmania",
    "Mandalay, Birmania",
    "Katmandú, Nepal",
    "Pokhara, Nepal",
    "Colombo, Sri Lanka",
    "Malé, Maldivas",
    "Almaty, Kazajistán",
    "Astana, Kazajistán",
    "Taskent, Uzbekistán",
    "Samarcanda, Uzbekistán",
    "Biskek, Kirguistán",
    "Ulán Bator, Mongolia",
    "Islamabad, Pakistán",
    "Lahore, Pakistán",
    "Karachi, Pakistán",
    "Daca, Bangladés",
    "Chittagong, Bangladés",
    "Wellington, Nueva Zelanda",
    "Christchurch, Nueva Zelanda",
    "Gold Coast, Australia",
    "Perth, Australia",
    "Adelaida, Australia",
    "Hobart, Australia",
    "Darwin, Australia",
    "Cairns, Australia",
    "Suva, Fiyi",
    "Papeete, Polinesia Francesa",
]

# Definición de intereses (para renderizar tarjetas desde Python)
INTERESTS_DEF = [
    {"key": "comida", "title": "Gastronomía", "icon": "fa-utensils", "image": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80", "desc": "Restaurantes, mercados y sabores locales."},
    {"key": "arte", "title": "Arte y Cultura", "icon": "fa-palette", "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpneyN9tGfVZ3glPCSjiDQmmSweitJn3QzbQ&s", "desc": "Museos, galerías y exposiciones."},
    {"key": "paseo", "title": "Paseos", "icon": "fa-person-walking", "image": "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=800&q=80", "desc": "Parques, plazas y caminatas."},
    {"key": "vistas", "title": "Vistas Panorámicas", "icon": "fa-binoculars", "image": "https://images.unsplash.com/photo-1506953823976-52e1fdc0149a?auto=format&fit=crop&w=800&q=80", "desc": "Miradores y paisajes increíbles."},
    {"key": "cafes", "title": "Cafés y Relax", "icon": "fa-mug-hot", "image": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80", "desc": "Ambiente relajado y buen café."},
    {"key": "museos", "title": "Historia y Museos", "icon": "fa-landmark", "image": "https://images.unsplash.com/photo-1566127444979-b3d2b654e3d7?auto=format&fit=crop&w=800&q=80", "desc": "Aprende sobre el pasado y la ciencia."},
    {"key": "aventura", "title": "Aventura", "icon": "fa-mountain", "image": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80", "desc": "Kayak, globo, senderos épicos."},
    {"key": "nocturna", "title": "Vida nocturna", "icon": "fa-moon", "image": "https://images.unsplash.com/photo-1505761671935-60b3a7427bad?auto=format&fit=crop&w=900&q=80", "desc": "Cocteles, jazz y rooftops."},
    {"key": "compras", "title": "Compras", "icon": "fa-shopping-bag", "image": "https://cdn.sanity.io/images/nxpteyfv/goguides/59aa10e938b999bcb34acdc4ffe461569df7ad21-1600x1066.jpg", "desc": "Mercados, outlets y hallazgos."},
    {"key": "playa", "title": "Playa y mar", "icon": "fa-umbrella-beach", "image": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80", "desc": "Veleros, snorkel y sunsets."},
    {"key": "bienestar", "title": "Bienestar", "icon": "fa-leaf", "image": "https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=900&q=80", "desc": "Spa, yoga y termales."},
]

# Destinos destacados (servidos desde backend para reducir JS en templates)
FEATURED_DESTINATIONS = [
    {"name": "Kyoto, Japón", "image": "https://st3.depositphotos.com/2051931/18142/i/450/depositphotos_181425574-stock-photo-japanese-pagoda-old-house-snow.jpg", "tagline": "Templos y jardines zen"},
    {"name": "Marrakech, Marruecos", "image": "https://assets3.thrillist.com/v1/image/2819216/792x526/scale;webp=auto;jpeg_quality=60;progressive.jpg", "tagline": "Medinas, zocos y té de menta"},
    {"name": "Reikiavik, Islandia", "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStaNRl2xdkzcgwi0v5rEle65yX9VdnoWQBJg&s", "tagline": "Auroras, cascadas y termas"},
    {"name": "Lisboa, Portugal", "image": "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=900&q=80", "tagline": "Tranvías, fado y miradores"},
    {"name": "Ciudad del Cabo, Sudáfrica", "image": "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?auto=format&fit=crop&w=900&q=80", "tagline": "Montaña de la Mesa y océano"},
    {"name": "Viena, Austria", "image": "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/11/6b/48/6d/photo0jpg.jpg?w=900&h=500&s=1", "tagline": "Palacios, ópera y café"},
    {"name": "Cartagena, Colombia", "image": "https://www.exp1.com/blog/wp-content/uploads/sites/7/2020/11/Day-4.jpeg", "tagline": "Murallas coloniales y mar Caribe"},
    {"name": "Seúl, Corea del Sur", "image": "https://images.unsplash.com/photo-1506816561089-5cc37b3aa9b0?fit=max&fm=jpg&ixid=M3wzNTY3MHwwfDF8YWxsfHx8fHx8fHx8MTY5ODkzMTI5Mnw&ixlib=rb-4.0.3&q=75&w=720&utm_medium=referral&utm_source=vocal.media", "tagline": "Palacios, K-food y neón"},
    {"name": "Nueva York, Estados Unidos", "image": "https://images.contentstack.io/v3/assets/blt06f605a34f1194ff/blt143cf9f3ca5a3a62/65610a0ed28c5a5f993deafe/BCC-2022-NYC-30THINGS-HEADER-e1649786857821-1-1536x1056.webp?format=webp&quality=60&width=1440", "tagline": "Skyline, Broadway y parques"},
    {"name": "Queenstown, Nueva Zelanda", "image": "https://www.newzealand.com/assets/externally-managed-assets/tbd-assets/tbd-folder-10092946/img-1731461073-7951-258451-tbd-asset__ExtRewriteWyJwbmciLCJqcGciXQ_aWxvdmVrZWxseQo_CropResizeWzk0MCw1MzAsOTAsImpwZyJd.jpg", "tagline": "Aventura y lagos cristalinos"},
    {"name": "Estambul, Turquía", "image": "https://www.traveltalktours.com/wp-content/smush-webp/2024/05/Choose-Your-Favorite-Destinations-in-Turkey-1024x683.jpg.webp", "tagline": "Mezquitas, bazares y Bosforo"},
    {"name": "Buenos Aires, Argentina", "image": "https://plus.unsplash.com/premium_photo-1697729901052-fe8900e24993?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8YnVlbm9zJTIwYWlyZXN8ZW58MHx8MHx8fDA%3D", "tagline": "Tango, asado y arquitectura europea"},
    {"name": "Astana, Kazajistán", "image": "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2c/91/c1/e3/caption.jpg?w=1200&h=-1&s=1", "tagline": "Arquitectura futurista y parques"},
]
